// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enftklpskwkixbuzyfsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVuZnRrbHBza3draXhidXp5ZnNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMjcyMjMsImV4cCI6MjA1NzgwMzIyM30.DM6MFC0GUMkFi3AQNs_v7EgBdad6eqIIix05mIzzcYo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);